id = "reader01"

bind = "0.0.0.0:8008"
grpc_bind = "0.0.0.0:7008"

nexus_addr = "localhost:7001"

[[sources]]
id = "shadiao"
label = "Shadiao Plus"
type = "wordpress"
source = "https://shadiao.plus/wp-json/wp/v2"
enabled = false
[[sources]]
id = "cnn-politics"
label = "CNN Politics"
type = "feed"
source = "http://rss.cnn.com/rss/cnn_allpolitics.rss"
enabled = true
[[sources]]
id = "bbc"
label = "BBC News"
type = "scrap"
source = "https://www.bbc.com/news"
enabled = false

[debug]
database = true
print_routes = false

[security]
internal_public_key = "keys/internal_public_key.pem"

[scraper]
expand_ua = "facebookexternalhit/1.1"
